name: Build and Publish

on:
  pull_request:
    branches:
      - Testing
  workflow_dispatch:
    inputs:
      branch:
        description: 'The current branch'
        default: Testing
        type: string
        required: false

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'Testing' }}
  NEXUS_URL: https://packages.nuxeo.com/repository/npm-public/
  NEXUS_REPOSITORY: npm-public
  NPM_CONFIG_USERCONFIG: /home/runner/.npmrc
  NEXUS_PASSWORD: ${{ secrets.PACKAGES_AUTH_TOKEN }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Set Registry Config
        run: |
          echo "//packages.nuxeo.com/repository/npm-public/:_authToken=${{ secrets.PACKAGES_AUTH_TOKEN }}" > ~/.npmrc
          npm config set @nuxeo:registry https://packages.nuxeo.com/repository/npm-public/ --global
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli
  
      - name: Install Dependencies
        run: npm install
    
      - name: Build Angular Project
        run: npm run build

      - name: Publish to Nexus
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
        run: npm publish --registry=https://packages.nuxeo.com/repository/npm-public/
