name: Build and Publish to Nexus

on:
  pull_request:
    branches:
      - DevOps-Testing
  workflow_dispatch:
    inputs:
      branch:
        description: 'The current branch'
        default: DevOps-Testing
        type: string
        required: false

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name || 'DevOps-Testing' }}
  NEXUS_URL: https://packages.nuxeo.com/repository/npm-public/ 
  NEXUS_REPOSITORY: npm-public 
  NEXUS_USERNAME: ${{ secrets.PACKAGES_AUTH_USER }} 
  NEXUS_PASSWORD: ${{ secrets.PACKAGES_AUTH_TOKEN }} 

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org/'

      - name: Set Registry Config
        run: |
          npm config set @hylandsoftware:registry https://npm.pkg.github.com --global
          npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GIT_TOKEN }} --global
          npm config set registry https://registry.npmjs.org/ --global

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install
    
      - name: Lint and Build
        run: npm run build

      - name: Zip Build Artifacts
        run: zip -r admin-console-ui.zip ./dist

      - name: Upload to Nexus
        env:
          NEXUS_URL: ${{ env.NEXUS_URL }}
          NEXUS_REPOSITORY: ${{ env.NEXUS_REPOSITORY }}
          NEXUS_USERNAME: ${{ env.NEXUS_USERNAME }}
          NEXUS_PASSWORD: ${{ env.NEXUS_PASSWORD }}
        run: |
          curl -u $NEXUS_USERNAME:$NEXUS_PASSWORD \
            --upload-file admin-console-ui.zip \
            "$NEXUS_URL/$NEXUS_REPOSITORY/admin-console-ui.zip"
