name: Build

on:
  pull_request:
    branches:
      - dev
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: dev
        type: string
        required: false
      debug:
          type: boolean
          description: enable debug
          default: false

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'dev' }}
  enabledebug: ${{ inputs.debug == true && '-vvv' || ''}}
  NEXUS_URL: https://packages.nuxeo.com/repository/npm-public/
  NEXUS_REPOSITORY: npm-public
  NODE_AUTH_TOKEN: ${{ secrets.NPM_ADMIN_TOKEN }}
  GIT_TOKEN: ${{ secrets.GIT_TOKEN}}
  NEW_VERSION: "2.0.0"


jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: ${{ env.NEXUS_URL }}
          scope: '@nuxeo'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      
      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                  <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Configure Additional Registries
        working-directory: nuxeo-admin-console-web/ang-src
        run: |
         echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" >> .npmrc
         
      # - name: Install Angular CLI
      #   run: npm install -g @angular/cli
  
      - name: Get Current Realease Vesrion
        run: |
          echo "CURRENT_VERSION=$(npx -c 'echo \"$npm_package_version\"')" >> $GITHUB_ENV


      - name: Update Realease Version Markeplace package
        env:
          CURRENT_VERSION: echo $(npx -c 'echo \"$npm_package_version\"')" 
          NEW_VERSION: ${{ env.NEW_VERSION }}
        run: |
         find . -type f -not -path "./node_modules/*" -regex ".*\.\(sample\|xml\)" -exec sed -i 's/'"1.0.0"'/'"$NEW_VERSION"'/g' {} \;
         echo "current verion: $CURRENT_VERSION , new version: $NEW_VERSION"
         cat pom.xml
         
      - name: Update Realease Version Npm package
        working-directory: nuxeo-admin-console-web/ang-src
        run: |
          npm version $NEW_VERSION
          cat package.json
      
      # - name: Build Angular Project
      #   run: mvn package 

      # - name: Publish on packages.nuxeo.com
      #   working-directory: nuxeo-admin-console-web/ang-src
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      #   run: |
      #     npm publish --registry https://packages.nuxeo.com/repository/npm-public/

      # - name: Push promoted Admin Console to Connect PREPROD
        # working-directory: nuxeo-admin-console-package/target
        # env:
        #   CONNECT_PREPROD_URL: https://nos-preprod-connect.nuxeocloud.com/nuxeo
        # run: curl -i -u "${{ secrets.CONNECT_PREPROD_AUTH }}" -F package=@nuxeo-admin-console-package-$NEW_VERSION-SNAPSHOT.zip "$CONNECT_PREPROD_URL/site/marketplace/upload?batch=true"