name: Build

on:
  push:
    branches:
      - DevOps-282

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  lint:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/lint.yaml@DevOps-282
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}

  utest:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/utest.yaml@DevOps-282
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}
    with:
      branch: DevOps-282

  a11y:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/a11y.yaml@DevOps-282
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      PACKAGES_AUTH_USER: ${{ secrets.PACKAGES_AUTH_USER }}
      PACKAGES_AUTH_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
    with:
      branch: DevOps-282

  ftest:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/ftest.yaml@DevOps-282
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      PACKAGES_AUTH_USER: ${{ secrets.PACKAGES_AUTH_USER }}
      PACKAGES_AUTH_TOKEN: ${{ secrets.PACKAGES_AUTH_TOKEN }}
    with:
      branch: DevOps-282

  build:
    needs: [lint, utest, a11y, ftest]
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Prepare environment
        run: |
          echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV
          echo "PACKAGE_VERSION=$(npx -c 'echo "$npm_package_version"')" >> $GITHUB_ENV

      - name: Get prerelease version
        run: |
          git fetch origin --tags
          RC_VERSION=$(git tag --sort=taggerdate --list "v${PACKAGE_VERSION/-SNAPSHOT}*" | tail -1 | tr -d '\n')
          echo "VERSION=$(npx semver -i prerelease --preid rc ${RC_VERSION:-$PACKAGE_VERSION}  | tr -d '\n')" >> $GITHUB_ENV

