name: Lint

on:
  pull_request:
    branches:
      - DevOps-282
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: DevOps-282
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'DevOps-282' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          node-version: 18
          scope: '@nuxeo'

      - name: Install
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm install

      - name: Lint
        run: npm run lint