name: Lint

on:
  pull_request:
    branches:
      - dev
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: dev
        type: string
        required: false

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'dev' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          node-version: 20
          scope: '@nuxeo'

      - name: Configure Additional Registries
        run: |
            npm config set @hylandsoftware:registry https://npm.pkg.github.com --global
            npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }} --global
            
      - name: Configure npm for Nexus Authentication
        run: |
            npm config set //packages.nuxeo.com/repository/npm-public/:_authToken=${{ secrets.NPM_ADMIN_TOKEN }} --global

      - name: Install @angular/cli
        run: npm install -g @angular/cli

      - name: Install
        run: npm install 
    
      - name: Lint
        run: npm run build
