name: Lint

on:
  pull_request:
    branches:
      - dev
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: dev
        type: string
        required: false

env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'dev' }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ env.BRANCH_NAME }}

      - name: Remove .npmrc file if exists
        run: |
          if [ -f .npmrc ]; then
            rm .npmrc
          fi
      - uses: actions/setup-node@v4
        with:
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          node-version: 20
          scope: '@nuxeo'

      - name: Configure Additional Registries
        run: |
            npm config set @hylandsoftware:registry https://npm.pkg.github.com --global
            npm config set //npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }} --global
            npm config set registry https://registry.npmjs.org/ --global
      - name: Install @angular/cli
        run: npm install -g @angular/cli

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint