name: Main

on:
  push:
    branches:
      - dev-test-1

  # Manually trigger the workflow
  workflow_dispatch:

jobs:
  lint:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/lint.yaml@dev-test-1
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 

  test:
    uses: nuxeo/nuxeo-admin-console-ui/.github/workflows/utest.yaml@dev-test-1
    secrets:
      NPM_PACKAGES_TOKEN: ${{ secrets.NPM_PACKAGES_TOKEN }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} 

  build:
    # needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: ${{ env.NEXUS_URL }}
          scope: '@nuxeo'

      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: 'Update settings.xml with server configuration'
        run: |
          echo '<settings>
              <servers>
                <server>
                  <id>maven-internal</id>
                  <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                  <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                </server>
              </servers>
              </settings>' > ~/.m2/settings.xml

      - name: Configure Additional Registries
        working-directory: nuxeo-admin-console-web/angular-app
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" >> .npmrc

      - name: Prepare environment
        run: |
          echo "BRANCH_NAME=${GITHUB_HEAD_REF##*/}" >> $GITHUB_ENV
          pushd nuxeo-admin-console-web/angular-app
          echo $(npx -c 'echo "$npm_package_version"')
          echo "PACKAGE_VERSION=$(npx -c 'echo "$npm_package_version"')" >> $GITHUB_ENV 
          popd

      - name: Test
        run: |
          echo "${{env.PACKAGE_VERSION}}" ${{env.PACKAGE_VERSION}}

          - name: Get prerelease version
          run: |
            git fetch origin --tags
            if [[ "${{ env.PACKAGE_VERSION }}" == *"-SNAPSHOT" ]]; then
              NEXT_PACKAGE_VERSION="${{ env.PACKAGE_VERSION%-SNAPSHOT}}-rc-0"
            elif [[ "${{ env.PACKAGE_VERSION }}" == *"-rc-"* ]]; then
              base_version=${{ env.PACKAGE_VERSION%-rc-* }}
              rc_number=${{ env.PACKAGE_VERSION##*-rc- }}
              rc_number=$((rc_number + 1))
              NEXT_PACKAGE_VERSION="$base_version-rc-$rc_number"
            else
              echo "Version format not recognized. Exiting."
              exit 1
            fi
            echo "NEXT_PACKAGE_VERSION=$NEXT_PACKAGE_VERSION" >> $GITHUB_ENV
            echo "VERSION=$(npx semver -i prerelease --preid rc ${RC_VERSION:-${{ env.PACKAGE_VERSION }}} | tr -d '\n')" >> $GITHUB_ENV
    

      - name: Update versions
        run: |
         find . -type f -not -path "./node_modules/*" -regex ".*\.\(yaml\|sample\|xml\)" -exec sed -i 's/'"${PACKAGE_VERSION}"'/'"${NEXT_PACKAGE_VERSION}"'/g' {} \;
      
      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install Dependencies
        working-directory: nuxeo-admin-console-web/angular-app
        run: npm install

      - name: Build Angular Project
        run: mvn package

      - name: Tag
        run: |
          git add package-lock.json nuxeo-admin-console-web/angular-app/package-lock.json
          git commit -a -m "Release ${NEXT_PACKAGE_VERSION}"
          git tag -a v${NEXT_PACKAGE_VERSION} -m "Release ${NEXT_PACKAGE_VERSION}"
          git push origin v${NEXT_PACKAGE_VERSION}

      - name: Publish on Pre Prod Marketplace
        working-directory: nuxeo-admin-console-package/target
        run: |
           echo "Publishing on Pre Prod Marketplace"
           ls
