name: Promote release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote (e.g.: )'
        required: true
      referenceBranch:
        description: 'Branch to be updated after the promotion'
        required: true
        default: 'main'
      dryRun:
        description: 'Run the workflow without pushing code or publishing artifacts'
        type: boolean
        required: false

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - run: echo "VERSION=$(echo '${{ github.event.inputs.version }}' | sed -e 's/-rc.[0-9]*//')" >> $GITHUB_ENV

      - name: Update Nuxeo Web admin console version to ${{ env.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          OLD_VERSION=$(npx -c 'echo "$npm_package_version"')
