name: Promote release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to promote (e.g.: )'
        required: true
      referenceBranch:
        description: 'Branch to be updated after the promotion'
        required: true
        default: 'main'
      dryRun:
        description: 'Run the workflow without pushing code or publishing artifacts'
        type: boolean
        required: false

jobs:
  promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://packages.nuxeo.com/repository/npm-public/'
          scope: '@nuxeo'

      - uses: actions/checkout@v2
        with:
          ref: v${{ github.event.inputs.version }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: git config user.name "nuxeo-webui-jx-bot" && git config user.email "webui@hyland.com"

      - run: echo "VERSION=$(echo '${{ github.event.inputs.version }}' | sed -e 's/-rc.[0-9]*//')" >> $GITHUB_ENV

      - name: Update Nuxeo Web UI version to ${{ env.VERSION }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          OLD_VERSION=$(npx -c 'echo "$npm_package_version"')
          npm version $VERSION --no-git-tag-version
          pushd packages/nuxeo-admin-console-ui-ftest/
          npm version $VERSION --no-git-tag-version
          popd

          find . -type f -not -path "./node_modules/*" -regex ".*\.\(yaml\|sample\|xml\)" -exec sed -i 's/'"$OLD_VERSION"'/'"$VERSION"'/g' {} \;
          # XXX: undo the padded lock (see WEBUI-140)
          sed -i -e 's/<admin-console-ui.package.version>.*<\/admin-console-ui.package.version>/<admin-console-ui.package.version>${project.version}<\/admin-console-ui.package.version>/g' plugin/admin-console-ui/marketplace/pom.xml
          npm i @nuxeo/testing-helpers@$VERSION --save-exact

      - name: Perform git release of Nuxeo Web UI ${{ env.VERSION }}
        run: |
          git commit -a -m "Release $VERSION"
          git tag -a v$VERSION -m "Release $VERSION"

      - if: ${{ github.event.inputs.dryRun == 'false' }}
        run: git push origin v$VERSION

      - name: Create Github release v${{ env.VERSION }}
        if: ${{ github.event.inputs.dryRun == 'false' }}
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}

      - name: Publish Nuxeo Admin Console UI FTest ${{ env.VERSION }}
        if: ${{ github.event.inputs.dryRun == 'false' }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pushd packages/nuxeo-admin-console-ui-ftest/
          npm publish --@nuxeo:registry=https://packages.nuxeo.com/repository/npm-public/
          popd
