# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_call:
    inputs:
      branch:
        description: 'The branch to Analyze'
        type: string
        required: true
    secrets:
      PACKAGES_AUTH_USER:
        description: 'PACKAGES_AUTH_USER'
        required: true
      PACKAGES_AUTH_TOKEN:
        description: 'PACKAGES_AUTH_TOKEN'
        required: true
      VERACODE_API_ID:
        description: 'VERACODE_API_ID'
        required: true
      VERACODE_API_KEY:
        description: 'VERACODE_API_KEY'
        required: true

env:
  REFERENCE_BRANCH: dev
  NPM_REPOSITORY: https://packages.nuxeo.com/repository/npm-public/
  BRANCH_NAME: ${{ github.head_ref || inputs.branch || 'dev' }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: read

jobs:
  # This workflow contains a job to build and submit pipeline scan, you will need to customize the build process accordingly and make sure the artifact you build is used as the file input to the pipeline scan file parameter
  sast-scan-build:
    # The type of runner that the job will run on
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:

    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it and copies all sources into ZIP file for submitting for analysis. Replace this section with your applications build steps
    - uses: actions/checkout@v4
      with:
          ref: ${{ env.BRANCH_NAME }}

    - uses: actions/setup-node@v4
      with:
          registry-url: ${{ env.NPM_REPOSITORY }}
          node-version: 20
          scope: '@nuxeo'

    - uses: actions/setup-java@v4
      with: 
          distribution: 'zulu'
          java-version: '17'

    - name: 'Update settings.xml with server configuration'
      run: |
        echo '<settings>
              <servers>
                  <server>
                    <id>maven-internal</id>
                    <username>${{ secrets.PACKAGES_AUTH_USER }}</username>
                    <password>${{ secrets.PACKAGES_AUTH_TOKEN }}</password>
                  </server>
                  </servers>
                </settings>' > ~/.m2/settings.xml
                
    - name: Configure Additional Registries
      working-directory: nuxeo-admin-console-web/angular-app
      run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GIT_TOKEN }}" >> .npmrc

    - name: Install Angular CLI
      run: npm install -g @angular/cli

    - name: Install Dependencies
      working-directory: nuxeo-admin-console-web/angular-app
      run: npm install
    
    - name: Delete Node Modules
      working-directory: nuxeo-admin-console-web/angular-app
      run: |
        rm -rf nuxeo-admin-console-web/angular-app/node_modules
       
    - name: Install zip
      run: sudo apt-get install zip

    - name: Zip nuxeo-admin-console
      working-directory: nuxeo-admin-console-web/angular-app
      run: |
        zip -r nuxeo-admin-console-ui.zip *

    - name: Upload ZIP as artifact
      uses: actions/upload-artifact@v4
      with:
        name: nuxeo-admin-console-ui
        path: nuxeo-admin-console-web/angular-app/nuxeo-admin-console-ui.zip
  
  scan:
    needs: scan-build
    permissions:
      contents: read
      security-events: write
      actions: read
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: nuxeo-admin-console-ui
          path: .

      - name: List downloaded artifact
        run: |
          ls -l
          pwd

      - name: Veracode Upload And Scan
        uses: veracode/veracode-uploadandscan-action@0.2.6
        with:
          appname: 'nuxeo-admin-console-ui'
          createprofile: false
          filepath: 'nuxeo-admin-console-ui.zip'
          vid: '${{ secrets.VERACODE_SECRET_API_ID }}'
          vkey: '${{ secrets.VERACODE_SECRET_KEY }}'
          sandboxname: 'master'
          scantimeout: 600
          include: '*.war, *.zip, *.js, *.html, *.css, *.json'
          criticality: 'High'
          includenewmodules: 'true'