name: Veraocde 

on:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  run-scheduled-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: dev-test-1

      - name: Run a script
        run: echo "This job runs every minute on the dev-test-1 branch"
